### ISSUE TITLE
Implement caesar cipher in a gtk-rs app

### ISSUE THREAD

**Issue by MateusRodCosta** [ArtemGr/bounty#1]
Implement the [caesar cipher](https://en.wikipedia.org/wiki/Caesar_cipher) in Rust for a gtk-rs app.

Bounty: USD 5

**Comment by ArtemGr** [comment]
Hey, @MateusRodCosta ! Thanks for coming up with this!
I'm curious, what makes it exciting for you to work on the cipher suite, and where will it take you?
Attaching the bounty now!

**Comment by MateusRodCosta** [comment]
Hi, the idea is actually to have a relatively complex GTK app created in Rust.

It just happened that implementing some ciphers were the idea that popped up in my head and that idea seemed both relatively easy and enough for me to learn more both about Rust and GTK.

I chose the following ciphers for the app: Caesar, Atbash, Vigenere, Rot13. From which Rot13 and Atbash are already implemented. Caesar is the next step and it's simple enough that I believe a USD 5 bounty is what it is worth.

After that I plan on implementing Vigenere (which I so far haven't managed to wrap my head around how it works). After all ciphers are implemented I will create an app icon, release on GitLab under GPLv3+ and try to publish it to Flathub.

The app so far looks like this:
![Captura de tela de 2021-01-04 15-55-54](https://user-images.githubusercontent.com/24463334/103569132-86055980-4ea5-11eb-958f-43873b6c001e.png)

**Comment by MateusRodCosta** [comment]
Hi, so this took a bit longer than I expected. Thanks for waiting anyway.

While I did finish the Caesar cipher early, I had decided that I would only make the app public after finishing all 4 ciphers, and the Vigenere cipher took a long time to understand and code (it's however just a more complex caesar cipher, so once I understood that, it was easy).

Anyway, the repo is at https://gitlab.com/MateusRodCosta/decypher

I still have to add a README with info on how to build, but the code is there and in a working state.

Code for all ciphers is located on src/cipher.rs

Remember that it's a very GNOME-centric app, so I don't know how easy it would be if you tried to compile it on Windows or Mac.

**Comment by ArtemGr** [comment]
Hey, @MateusRodCosta !
Thanks for participating in the experiment!

What is something non-technical that you've learned while working on this?
Where would you post about it (or have posted), and how would you approach telling the world about it?

**Comment by MateusRodCosta** [comment]
> Hey, @MateusRodCosta !
> Thanks for participating in the experiment!
> 
> What is something non-technical that you've learned while working on this?
> Where would you post about it (or have posted), and how would you approach telling the world about it?

@ArtemGr Hey, sorry for the delay, I have been somewhat busy these last days.

Non-technical stuff.... Let me think.

I think I learned the ciphers, from which the Vigenere was the hardest and I only ever managed to learn how to implement that one by looking at some other code for it in C.

While not something new, when I have issues with or questions about Rust, I usually ask for help in some of the Matrix channels for the Rust language, and generally I get a lot of help there! Not something new, but it's nice knowing that you can leave your question there and a while later you would get lots of tips!

So... In the end, there are a few small details to finish this: a About dialog, an app icon, doing the AppStream data stuff, Putting it on Flathub, adding a Readme with info on how to build it. At some point, I would most likely want to make some kind of "release announcement" on my blog, which could possibly have some info on how the app was done.
