### ISSUE TITLE
Write initial documentation for Griffin

### ISSUE THREAD

**Issue by giraffekey** [ArtemGr/bounty#10]
[Griffin](https://github.com/GiraffeKey/griffin) needs to get some documentation started.

As a start, a page can be written about the query language used in find, update and replace operations. It is fairly straightforward and easy to understand but there is nothing written out that goes into it in great detail. It's pretty much the same as Mango though there may be minor differences.

The page can be written in the Github Wiki, perhaps later Griffin will gain its own website but for now it's the markdown files that are important.

**Comment by ArtemGr** [comment]
Hey, @GiraffeKey !
So nice to see you!

Can you tell us a bit about https://github.com/GiraffeKey/kadis ? How does it compare with GUN? What's cool about it? What's not? Is griffin a development of the kadis idea somehow?

**Comment by giraffekey** [comment]
Originally I was thinking of a networking stack which is mostly user data based but stored public data in a DHT. It's essentially just to give Kademlia some extra functionality. However now I am thinking BigchainDB or similar would be better. I may experiment with emulating blockchain functionality in Griffin using the Avalanche consensus protocol.

**Comment by giraffekey** [comment]
Kadis has no connection to Griffin's usage of Kademlia.

**Comment by ArtemGr** [comment]
Awesome!
I'd very much like to see that!
I mean, the process of adding the Avalanche!

**Comment by agarwalrounak** [comment]
Hi @GiraffeKey and @ArtemGr! 
Can I work on this issue to create an initial documentation for Griffin? 
Will I be eligible for the bounty?

**Comment by giraffekey** [comment]
Yes.

You can edit this wiki page: https://github.com/GiraffeKey/griffin/wiki/Query-language

You can find the implementation in the "matches" function: https://github.com/GiraffeKey/griffin/blob/main/core/lib/util.js

The query operators are similar to the ones here: https://docs.mongodb.com/manual/reference/operator/query/

**Comment by agarwalrounak** [comment]
I am not able to edit the wiki page. The access permission for wikis is limited to collaborators only. You will need to change the access permissions: https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis  
Or
I can open a PR with the markdown file and it can be added to the wiki later.

Let me know what works for you.

**Comment by giraffekey** [comment]
A docs folder with markdown may be more useful because they may be used to generate website content later on.

**Comment by ArtemGr** [comment]
Files also show up in the GitHub statistics/benchmarks  )

**Comment by agarwalrounak** [comment]
I will get started right away with creating the initial documentation. 

Currently looking at the implementation of query operators in the `matches` function in `util.js` and also going through the mongodb docs. Excited to be learning a lot from this!

Will send a PR containing basic documentation to Griffin repository soon!

**Comment by ArtemGr** [comment]
Am happy to hear that, @agarwalrounak !
Do you make selfies, and/or screen capturing webcam videos?

**Comment by agarwalrounak** [comment]
@ArtemGr No. But why?

**Comment by ArtemGr** [comment]
It's a theory of mine that when people attach a selfie to their work, something quite magical eventually happens   :-p

**Comment by agarwalrounak** [comment]
Opened PR https://github.com/GiraffeKey/griffin/pull/5 

Should be enough to get Griffin started with some documentation.

**Comment by ArtemGr** [comment]
Nice!

Rounak, what else do you do?
And are you using or going to use the Griffin now?

**Comment by agarwalrounak** [comment]
I will surely use Griffin in my projects.

**Comment by agarwalrounak** [comment]
As of now, @GiraffeKey is performing a rewrite of Griffin. After that is done, I am willing to add implementation of new operators for Griffin. 

@GiraffeKey by when do you expect the rewrite to be completed?

**Comment by giraffekey** [comment]
Within the next couple of days, this rewrite will be a lot more usable than the initial one. The logic is mostly the same and the initial version only took two days so.

**Comment by giraffekey** [comment]
There are some things you might be able to help with when I finish up some things later this morning (rn it's 1:30am and I'm going to bed soon).

Since the logic is similar, once I rewrite the find operation logic you can prob compare the old & new versions and figure out how to do insert, update, etc.

And I will also need to set up a unit testing suite. I'll do the initial setup, if you want to add some more tests that'd be helpful as well.

Aside from the rewrite I have some other things to experiment with so a decrease in the total work load would be nice.

Do you happen to use Discord?

**Comment by agarwalrounak** [comment]
Awesome! Looking forward to the changes.

Yes, I do use Discord.

**Comment by ArtemGr** [comment]
@GiraffeKey and do you use Telegram? It's cool to [telescope](https://telegram.org/blog/video-messages-and-telescope) once in a while. @agarwalrounak found me on Telegram recently. There's also https://t.me/bounty_aga

**Comment by giraffekey** [comment]
I moved and had my internet out for a while. Updates to Griffin are up!

**Comment by ArtemGr** [comment]
Wow, nice nick!
Didn't know you can change that!  D
