### ISSUE TITLE
script and library in one

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#23]
Figure how to allow for invoking a NodeJS script from the command line while ALSO using it as a library with exports.

The issue is solved when we can demonstrate invoking the same JavaScript file J from the command line, `node J --arguments`, and with `npm install` from another package.

https://github.com/ArtemGr/bounty/blob/549cc6c94eb67b1d9beea9eead5a1c8d53ecfcfc/google-drive/google-drive.js#L3

**Comment by Nabeelhassan** [comment]
Hey mate, have you seen https://github.com/super-cache-money/make-runnable? it is able to run 'require' scripts and has a few examples. I tested them out. They work fine for function exports but no good for class exports.

what type of nodejs script areyou planning to execute ?

**Comment by ArtemGr** [comment]
Hi, Nabeel!
Looks cool, will give it a go!

> what type of nodejs script areyou planning to execute ?

Function exports will do!
Most libraries should be runnable, IMHO, and vice versa.

make-runnable might be too heavy for the smaller libraries (such as [log.js](https://gist.github.com/ArtemGr/25fad725870b0ada74df2bce7d115cc1) or [termkit-pause](https://gist.github.com/ArtemGr/1e668405bb07bb330cc4717f6b8f891e)) but we can check their code to see how they differentiate between the command line and library modes.

For a use case, [termkit-pause](https://gist.github.com/ArtemGr/1e668405bb07bb330cc4717f6b8f891e) here, when invoked from command line, should demostrate how it implements the pause.

**Comment by mkamalkayani** [comment]
You can execute functions in the .js files in the command line like this:

`node -e 'require("./index.js").pause()' `

**Comment by ArtemGr** [comment]
Following the example of make-runnable I've found https://nodejs.org/dist/latest-v15.x/docs/api/modules.html#modules_accessing_the_main_module

cf. the changes in https://gist.github.com/ArtemGr/1e668405bb07bb330cc4717f6b8f891e/revisions
![image](https://user-images.githubusercontent.com/41847/110784402-819b4b00-821e-11eb-9ae4-7efe69c723e9.png)

Also using the form suggested by @mkamalkayani in package.json

@Nabeelhassan , @mkamalkayani , you're welcome to claim the bounties (I'll wait a few days before recycling)
