### ISSUE TITLE
given youtube video ID, grab title and description

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#24]
## user story

As someone who knows an ID of a youtube video, I can run a NodeJS command to grab the title and description, in order to save time on manual copy-pasting.

## acceptance test

Running `node grab-youtube-title.js https://youtu.be/5hVmeOCJjOU` we should see something like

    title: A Brief History of Quantum Mechanics - with Sean Carroll
    channel: The Royal Institution
    channel-id: UCYeF244yNGuFefuFKqxIAXw
    user: TheRoyalInstitution
    description: The mysterious world of quantum mechanics...

## use cases

Imagine an editor where we are taking some notes. A youtube video is mentioned there by its URL. When the mouse hovers over the video ID, we might want to show the author's name and title, and a part of description, in the on-hover popup.

A typical use case is also to show a title and a preview picture when a video URL is mentioned in a chat.

## discussion

I haven't investigated the subject of grabbing youtube metadata yet, but prelimiarily I see some possible directions:  
`1)` maybe there is an API by Google which we can reuse (via HTTP requiest or through a NodeJS library)  
`2)` might visit youtube with [playwright](https://www.npmjs.com/package/playwright)
`3)` might look at [youtube-dl](https://en.wikipedia.org/wiki/Youtube-dl)

**Comment by Nabeelhassan** [comment]
There are a npm packages I found [simple-youtube-api](https://www.npmjs.com/package/simple-youtube-api). It has 80k downloads, but the package is no longer maintained so its a bad option.

The official youtube api docs has a sample. 
`https://developers.google.com/youtube/v3/quickstart/nodejs`

This might be the right way to go in my opinion. The only npm package required is the googleapis for oauth, so no hassle there.

**Comment by ArtemGr** [comment]
Looks like the official API requires a secret similar to https://github.com/ArtemGr/bounty/tree/main/google-drive. Fine by me.

**Comment by Nabeelhassan** [comment]
Check your dm on fiver. I have sent the script as zip file.

Follow the [guide](https://developers.google.com/youtube/v3/quickstart/nodejs), install the client libraries and setup an app with oauth.

I couldn't get the user name as it was not provided in the response. [More on Video endpoint](https://developers.google.com/youtube/v3/docs/videos)

It will also work for multiple urls too.
example:  `node grab-youtube-title.js https://youtu.be/5hVmeOCJjOU https://youtu.be/5hVmeOCJjOU `

**Comment by srevinsaju** [comment]
Is this bounty solved?

**Comment by ArtemGr** [comment]
@srevinsaju , looking at https://github.com/ArtemGr/bounty/commit/43b8e74b1f1ade6f103acc083071f708ba8cd233

**Comment by srevinsaju** [comment]
@ArtemGr  Ok cool, Thanks for the commit. I will share a link to a private gist of my implementation,

**Comment by ArtemGr** [comment]
@srevinsaju , PR to youtube/ ?

**Comment by srevinsaju** [comment]
Ok

**Comment by ArtemGr** [comment]
@jdmiii, how it's going with https://github.com/jdmiii/grab-youtube-title, what's your next step?

Just checked @Nabeelhassan 's version and it works. We can have both the API and HTTP modes though.

@Ich5003 , I see a question on Bountysource,

![image](https://user-images.githubusercontent.com/41847/111676091-0bc54f80-87db-11eb-8608-e596c9c9d63d.png)

but I can not answer you there.

**Comment by Nabeelhassan** [comment]
well I have seen your code @srevinsaju. The package you are using youtubei in-turn is using youtube v1 api which will be [depreciate](https://developers.google.com/youtube/v1_deprecation_notice) 3 years after v2.

My code using v3. I dont think have access tokens would hurt as it is the way to go.

**Comment by ArtemGr** [comment]
I like both versions, will make them interchangeable maybe.

**Comment by srevinsaju** [comment]
Yes, I agree @Nabeelhassan . Your implementation will work in the long run.

 Sometimes, some prefer to get stuff running as quick as possible, (i.e without the hassle of getting API keys for example), that might be a possible use case. I appreciate your implementation.

**Comment by ArtemGr** [comment]
@srevinsaju , what do you like about Open Source?

**Comment by srevinsaju** [comment]
I love how we can learn from different people, I love to learn new things. I love the collaboration in open source. Possibly, its 'open source' what built me, taught me. I had awesome mentors, everyone is willing to help, everyone has opinions, and everyone's opinions are 'valued'. Your education, degree, age, .. nothing matters in open source. If you have passion, you can even submit a patch into any project, big or small, into the Linux kernel, or a hello world repository, if its good enough!

I simply :heart: open source. Its just awesome.

**Comment by ArtemGr** [comment]
I've just discovered https://archivy.github.io/difference/ through @srevinsaju 's profile and I share the idea of getting some of our data back. YouTube tool is the first in a series of tools aimed at simplifying the structured access and synchronization of public and personal data(sets).

**Comment by srevinsaju** [comment]
Agreed, for videos, `youtube-dl` as mentioned in this PR is simply awesome, for websites, articles and blog posts, [Archivy](https://github.com/archivy/archivy) and [ArchiveBox](https://github.com/archivebox) (both are awesome tools, they help each other, and work for the same mission). Someday, I might add a youtube-dl feature to Archivy which would automatically download the video embedded too. Thanks for the suggestion :innocent: .

**Comment by ArtemGr** [comment]
Can we experiment with making a Python wrapper that would allow to use these/such JS tools directly?

**Comment by srevinsaju** [comment]
I can write a python script and a golang script to do the same thing which we did in javascript. Would that be good?

**Comment by ArtemGr** [comment]
I have other tools in mind, some of them on playwright, and duplicating them in python seems like a nonstarter to me.
I mean, everything can be ported or recreated eventually, but it would be a non-goal right now.

**Comment by srevinsaju** [comment]
oh, ok. What is your requirement? I didnt understand how we could make a python wrapper for the same

**Comment by srevinsaju** [comment]
if you are thinking of making it accessible from the terminal in one command, an, `npm install -g .` would create `youtube-title-grab` script, which can be then used to access the node script from the terminal.

```bash
$ youtube-title-grab https://youtu.be/....
```

would then get the metadata

**Comment by ArtemGr** [comment]
I mean Archivy / ArchiveBox [plugin(s)](https://archivy.github.io/plugins/), using JS tools underneath.
Let's maybe get back to it once we have more tools there.

**Comment by srevinsaju** [comment]
Oh, a simple command which can automatically run all this scripts, and this repository can act like a collection of utility scripts?
Thats sounds like a good idea.

```bash
something youtube-title-grab
something google-drive
something ...
```
you mean like this?

**Comment by ArtemGr** [comment]
Yep. The tools there will likely emit JSON and YAML and will have a JS API as well.
A python wrapper might also be useful, say, in kaggle/colab.

**Comment by srevinsaju** [comment]
Cool, that would be awesome. Actually, a similar idea has been featured on Hacker News https://ianthehenry.com/posts/sd-my-script-directory/ (https://news.ycombinator.com/item?id=26461051). The author puts forward a similar idea, but he thinks it could be considerably improved. Possibly, we might like to get some inspiration from his article too.

**Comment by ArtemGr** [comment]
Will take a look!
And I'll roll out a few more tools in a month to give a sense on the shape of APIs.

**Comment by matheusn17** [comment]
HI! 
Already solved the issue, if you still need it.

The solution use the V3 youtube API, through HTTPS request. It also can retrieve any information related to the video avaible through the youtube API. You just need your API KEY(theres is a temporary one on the code for test purposes)

**Comment by SuspiciousLookingOwl** [comment]
> well I have seen your code @srevinsaju. The package you are using youtubei in-turn is using youtube v1 api which will be [depreciate](https://developers.google.com/youtube/v1_deprecation_notice) 3 years after v2.
> 
> My code using v3. I dont think have access tokens would hurt as it is the way to go.

`youtubei` doesn't use the [official API](https://developers.google.com/youtube/v3), it uses the internal API for the web client, hence why it doesn't require any API key. I'm pretty sure they are different.

**Comment by ArtemGr** [comment]
@srevinsaju , so here's what I've been talking about:

https://github.com/ArtemGr/bounty/tree/main/data/steam - a command to fetch the list of Steam games

https://github.com/ArtemGr/bounty/tree/main/data/firefox - a command to fetch the list of firefox tabs

https://github.com/ArtemGr/bounty/tree/main/data/youtube-music - a command to fetch songs from a YouTube playlist

Question is, would you like to wrap such JS scripts in Python, for Archivy and also for general use?

My thinking is that a common API might emerge for wrapping such scripts.

**Comment by srevinsaju** [comment]
Its possible, and it looks like a really good idea.

> Question is, would you like to wrap such JS scripts in Python, for Archivy and also for general use?

I can try to create a wrapper, right now I am held up with other projects. Let me know if you are posting a bounty on this, to speed up the work 😄

**Comment by ArtemGr** [comment]
@srevinsaju,

Sure thing!

Bounty posted, https://www.bountysource.com/issues/98280949-wrap-nodejs-data-acquisition-for-python
to help you with allocating some time 😃

**Comment by srevinsaju** [comment]
Awesome, I will get to working and will submit a PR, probably today :tada:
