### ISSUE TITLE
find or recreate binprint in JS

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#26]
In Rust I have this function to log untrusted data (such as the contents of the Origin HTTP header) in order to prevent [log attacks](https://owasp.org/www-community/attacks/Log_Injection):

https://github.com/ArtemGr/gstuff.rs/blob/0e42dcddf25dd9cd53f25ee75ec50e417310f9d4/gstuff.rs#L584

```
/// Helps logging binary data (particularly with text-readable parts, such as bencode, netstring)
/// by replacing all the non-printable bytes with the `blank` character.
pub fn binprint (bin: &[u8], blank: u8) -> String {
  let mut bin: Vec<u8> = bin.into();
  for ch in bin.iter_mut() {if *ch < 0x20 || *ch >= 0x7F {*ch = blank}}
  unsafe {String::from_utf8_unchecked (bin)}}
```

Let's reproduce and/or find it in JS.

## discussion

In JS a regular expression might be appropriate, given they JIT them.

**Comment by TheOsch** [comment]
Here it is, in the pull request #27

**Comment by ArtemGr** [comment]
Interesting, thanks!

**Comment by TheOsch** [comment]
Excuse me please, can you accept my claim at BountySource? Need money.

**Comment by ArtemGr** [comment]
Done!

**Comment by TheOsch** [comment]
Thank you!
