### ISSUE TITLE
paint on ObservableHQ canvas

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#31]
In order to make it easier for people to make interactive canvas drawings and animations.

Find or make an ObservableHQ that [clearly](https://en.wikipedia.org/wiki/Minimal_working_example) demonstrates mouse handling on a canvas element, translating mouse position and clicks into events and coordinates handled in the canvas drawing code.

Might be a fork of https://observablehq.com/@artemgr/canvas-animation-template.

See also https://www.reddit.com/r/learnjavascript/comments/1gghzv/a_paint_game_in_canvas_and_vanilla_javascript/.

Should be a plain HTML5 canvas, with no extra dependencies (that is, no d3 and friends).

**Comment by it-baron** [comment]
completed 
https://observablehq.com/@akud82/canvas-animation-template

**Comment by ArtemGr** [comment]
Awesome, thanks!  <3
