### ISSUE TITLE
wrap NodeJS data acquisition for Python/Archivy

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#32]
cf. https://github.com/ArtemGr/bounty/issues/24#issuecomment-832596839

**Comment by ArtemGr** [comment]
https://youtu.be/NIKBYBvIk2M, watch at 2x  =

**Comment by ArtemGr** [comment]
https://youtu.be/NIKBYBvIk2M, watch at 2x  =

**Comment by srevinsaju** [comment]
Cool, also take a look at https://github.com/ArtemGr/bounty/tree/main/wrap, for the README.md and setup information. My test system was Linux, but I have added some basic code to handle windows environment too. Let me know if the `README.md` needs to improve. Looking at your video, I felt that I need to include more descriptive documentation in the code, which I will cover in an upcoming pull request.

**Comment by ArtemGr** [comment]
Yeah, I'll look from the other end next time.
Have a notion to see it in action by using it as a library from a colab notebook or something like that.
