### ISSUE TITLE
port MNIST download from JS

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#34]
Moving AI research from JS to Python we should maybe port [`load-mnist.js`](https://github.com/ArtemGr/bounty/blob/1621256/data/elm/load-mnist.js) to Python or Rust, to make MNIST more easily accessible from the various AI experiments.

cf.
https://www.kaggle.com/oddrationale/mnist-in-csv on the easy-to-use CSV format  
http://yann.lecun.com/exdb/mnist/ MNIST DATABASE, along with published test error rates

**Comment by TheOsch2** [comment]
I feel it's a temptive task. I'd try to make it in a few days if nobody would make it before me.

**Comment by ArtemGr** [comment]
Sounds good!
I can only offer a small bounty here, like $39.

**Comment by ArtemGr** [comment]
In Python we're currently experimenting with the built-in `http.client` (for streaming WARCs from Common Crawl, and to minimize overhead), so it is also preferable here (to compound on the experience).
Example:

```
import http.client
c = http.client.HTTPSConnection('shops.mercatos.net')
c.request('GET', '/ru/')
r = c.getresponse()
print(r.status)
```

p.s. Looks like [`requests`](https://pypi.org/project/requests/) is also all right.
p.s. [tf.keras.utils.get_file](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file)?

**Comment by ArtemGr** [comment]
Forgot about this Rust script, https://github.com/ArtemGr/bounty/blob/dabcf6e/data/elm/mnist.rs. I'll simply call it from Python if needed. TY.

**Comment by ArtemGr** [comment]
With `tensorflow` available in Python, obtaining MNIST can be reduced to `keras.datasets.mnist.load_data()`.

p.s. There is also https://github.com/LaurentMazare/tch-rs/blob/4325d3d/src/vision/mnist.rs.

**Comment by ArtemGr** [comment]
A working example:
https://github.com/ArtemGr/bounty/blob/71c8c1e58ba7dfc858b6cd802283be156c30e7d5/data/math/jax-adabelief.py#L128-L137
