### ISSUE TITLE
Port binary encoding from Rust to Python

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#38]
https://github.com/ArtemGr/bounty/blob/838e5a95e18627d124c0ddd43e02894767eb6063/data/common-crawl/csv-test.py#L5-L18

**Comment by TheOsch** [comment]
There are two solutions: by using replace() or just like it's made in Rust, character by character. Now I'm measuring which is faster. Will send a PR in a couple of hours.

**Comment by ArtemGr** [comment]
We're working in binary mode (fits well with memory mapping tricks, etc).
