### ISSUE TITLE
do nothing

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#4]
Do nothing. Exactly nothing. Time it. Tell us, how did it go?

**Comment by andrew-ld** [comment]
done.

**Comment by ArtemGr** [comment]
Awesome! How did it go, @andrew-ld ?

**Comment by andrew-ld** [comment]
it was like automatic breathing

**Comment by ArtemGr** [comment]
lol. all right!
bounty's yours!

what kind of rewards do you like besides a monetary bounty, can I ask?
