### ISSUE TITLE
 take a break. go out and make a picture

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#5]
Stretch your legs  D
Send us a selfie to prove you did

**Comment by andrew-ld** [comment]
![Screenshot_20210108_200602](https://user-images.githubusercontent.com/43882924/104054199-f1746180-51ec-11eb-934b-711d5f653130.png)

**Comment by ArtemGr** [comment]
Got a picture from @andrew-ld, but then it disappeared. What's up, @andrew-ld?

**Comment by andrew-ld** [comment]
privacy problems, I will take a picture in a more distant place

**Comment by ArtemGr** [comment]
You take opsec seriously in general? Proxies, tor?

**Comment by andrew-ld** [comment]
no

**Comment by ArtemGr** [comment]
![image](https://user-images.githubusercontent.com/41847/104106865-65564e80-526d-11eb-8fb6-3fc5dacc4a71.png)

**Comment by nok-ko** [comment]
Sent in my own picture, for what that's worth. 😄

**Comment by ArtemGr** [comment]
@nok-ko , nice!
Thanks for taking a walk!

Closing, do the claim!

We did a similar experiment at https://www.freelancer.com/contest/take-a-break-go-out-and-make-a-picture-1873762/entries
Got some positive feedback there  D
Check it out if you want to see more of the selfies!  D

(Positive feedback also [on Upwork](https://www.upwork.com/ab/applicants/1347469384349327360/job-details), but you wouldn't see the comments there)

p.s. What do you think? Should we make more of such bounties on BountySource, or is it something that only Freelance.com folks would appreciate?

**Comment by nok-ko** [comment]
> @nok-ko , nice!
> Thanks for taking a walk!
> 
> Closing, do the claim!
> 
> We did a similar experiment at [freelancer.com/contest/take-a-break-go-out-and-make-a-picture-1873762/entries](https://www.freelancer.com/contest/take-a-break-go-out-and-make-a-picture-1873762/entries)
> Got some positive feedback there D
> Check it out if you want to see more of the selfies! D
> 
> (Positive feedback also [on Upwork](https://www.upwork.com/ab/applicants/1347469384349327360/job-details), but you wouldn't see the comments there)
> 
> p.s. What do you think? Should we make more of such bounties on BountySource, or is it something that only Freelance.com folks would appreciate?

I found it was nice to come across it as I was scrolling through Bountysource. (Although they still haven't updated the issue's status as being closed.. >,>) I'm quite new to OSS bounties, so at least I found it nice.
