### ISSUE TITLE
suggest bounty priorities

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#6]
Tell us what kind of priorities a bounty should have?

And by priorities I mean not the external ones, like this here bounty is high priority and this one is low, but internal priorities, communicating our nonspecific preferences regarding how a particular bounty should be handled.

(And what priorities it should have not, to keep them implicit?)
(And how best to communicate these?)

**Comment by andrew-ld** [comment]
bounty should have a higher or lower priority based on multiple factors, each factor will carry its own weight.

- The largest factor to consider should be the engineering complexity to perform an analysis and hypothetical resolution of the problem.

- The second factor should be the time required to go from hypothesis to implementation.

- The third factor should be the cultural background required to solve the problem

**Comment by ArtemGr** [comment]
We can probably communicate how much time and/or effort we'd like to be allocated to initial research, but how should we communicate the preferences regarding the cultural background? Freeform folksonomy (cultural tags)?

p.s. Also, do we really know how complex or time consuming the initial research would be?
Will that metric work as a (suggested) iterative communication between the parties?

p.s. I guess we should ask the task author whether they think they know best? Maybe the task is a Simple problem, and the author expects it to be resolved without research. Or maybe the task is a Complex problem, but the author does not understand the need for research, and we should help capturing this.

**Comment by andrew-ld** [comment]
- but how should we communicate the preferences regarding the cultural background?: tags are inserted in the request in which is inserted in a generic way the main things that you think are required?

for example if it is a computer problem and is required the relationship of a software with libraries and specific languages you could inform the user with the tags that is required a cultural background on those specific tools, to determine whether a tool and more or less detected need to do a little research and understand if that tool can be easily learned without any further basis or you can use it even if you do not know anything about that area

- Also, do we really know how complex or time consuming the initial research would be?
Will that metric work as a (suggested) iterative communication between the parties?

in the world of research and development is always made an initial estimate of how complex and elaborate is the problem to be solved, who is of that specific field will give you the answer from personal experience

- I guess we should ask the task author whether they think they know best? Maybe the task is a Simple problem, and the author expects it to be resolved without research. Or maybe the task is a Complex problem, but the author does not understand the need for research, and we should help capturing this?

It would be necessary to have a voting system so more people can actually determine the weight of the points I have listed

**Comment by ArtemGr** [comment]
I see!

Is the culture similar to the skill tags we have on Upwork and Freelance, or is it different? A superset?

**Comment by andrew-ld** [comment]
it takes generic tags to start talking about the scope of the problem (for example: math, biology) then some specific tags on the topic (for example: java, async programming)

**Comment by andrew-ld** [comment]
@ArtemGr news?

**Comment by ArtemGr** [comment]
Wanted to give it a proper look later, when I have certain things nailed down, but it might be a while. Has been a very useful input nevertheless.

I'm thinking of a tool and/or simply a document that would suggest such internal priorities, kind of a cheatsheet when filing an issue, and also a place for people to go see what the hell we are talking about  D

( precedence of such documents: https://chris.beams.io/posts/git-commit/, https://keepachangelog.com/en/1.0.0/ )

**Comment by ArtemGr** [comment]
cf. https://github.com/ArtemGr/gun/commit/6d885542866d02d755ac442b55a59eb4864c2231 (distance)

**Comment by ArtemGr** [comment]
Started an ObservableHQ document/interface, https://observablehq.com/@artemgr/open-source-bounty-guide

**Comment by ArtemGr** [comment]
Might be interesting to see how this idea evolved: https://observablehq.com/@artemgr/pomodoro-freelance

**Comment by ArtemGr** [comment]
Related to this are benchmarks, cf. https://github.com/ArtemGr/bounty/commit/904e84187874b5cbd3dbe420c264b6269f2676f8
