### ISSUE TITLE
read a book about Qualitative Interviewing

### ISSUE THREAD

**Issue by DarkEclipse847** [ArtemGr/bounty#7]
I need to improve my skills in it, so I want to read "Learning From Strangers" by Robert Weiss

**Comment by ArtemGr** [comment]
Hey, @DarkEclipse847 !
Let's make it about just a chapter or two, to keep the tasks small!
Godspeed digging into the book!

**Comment by DarkEclipse847** [comment]
> Hey, @DarkEclipse847 !
> Let's make it about just a chapter or two, to keep the tasks small!
> Godspeed digging into the book!

Kk

**Comment by DarkEclipse847** [comment]
What do you mean while saying chapter two? :D
Second chapter in *Part* 1 or Second *Part* of the book

**Comment by ArtemGr** [comment]
Had just the second chapter in mind!

**Comment by DarkEclipse847** [comment]
## Introduction
 *If i will have any additional thoughts about it i will add them to github or personally to telegram*
 Firstly, In second chapter we can see some introduction part that we need to pay attention.
 Qualitative Interviewing is not always about numerical data or something, it's about psychology and communication with colleagues/friends.
 Collecting such information is great for understanding people.
 Cool thing there is that we can adapt questions for different groups of people
## Main Part
 Sooo, I dont't know what to write about, so i will try to set out my thoughts
 We can see in excerpt, that quialitative interviewing give us more information than simple sociological poll for example.
 It's like an open form of quizes and interviews.
 In this excerpt interviewer is too cagey, he could answer something more concrete cause interviewer is like a guide who conducts through topics.
 *"In the qualitative interview the respondent provides information while the interviewer, as a representative of the study, is responsible for directing the respondent to the topics that matter to the study."*
 He must act this way. In that case we see right communication with respondent, but I think that there is an other way to do qualitative interviews.
 I think that we can improve our skills in it by representing interview like a conversation.
 More warmer, more comfortable for respondent.

**Comment by ArtemGr** [comment]
Thanks for doing this, @DarkEclipse847 !
Did you like the interviewing examples in the book?
What will you read next?

**Comment by DarkEclipse847** [comment]
Yep, I like it, there's comfortble table in Part 4, check it out!
Thinking of reading some books about selfhypnosys
Btw if you have some good books please tell me their titles

**Comment by ArtemGr** [comment]
That's a tough one! There is no single book. On one hand, SH can be described sufficiently in one paragraph (as done by Ian Rowland). On another, one might want to [reinvent](https://slightlyeastofnew.com/2020/10/13/peeringly-deeply/) the thing. I'll likely get back to you on Telegram.
