### ISSUE TITLE
Add indexes to Griffin

### ISSUE THREAD

**Issue by giraffekey** [ArtemGr/bounty#8]
Add indexes to [Griffin](https://github.com/GiraffeKey/griffin) that follows the spec [here](https://docs.mongodb.com/manual/indexes/).

In Griffin it would be in the form of separate collections that are edited upon writes and read without attempted sorting if the index exists. This adds more overhead to writes but speeds up reads.

**Comment by ArtemGr** [comment]
Hey, @GiraffeKey ! Nice to see you here!

And glad to see your task!
Neat!

I've posted a bit of a bounty.

![image](https://user-images.githubusercontent.com/41847/104136197-82f8e600-5349-11eb-8cc9-e124843d720f.png)

Will add 63 more if you'd make a video or a blog (or a tweet!) - about this new feature of index collections in Griffin - and post it on a social media somewhere!

![image](https://user-images.githubusercontent.com/41847/104136281-fac71080-5349-11eb-93a9-a19ee513cd92.png)

**Comment by giraffekey** [comment]
https://airtext.xyz/blog/giraffekey.id.blockstack/OHQQu72pPdVNZ7k

**Comment by giraffekey** [comment]
https://github.com/GiraffeKey/griffin

It's done.

One thing of note is I decided not to automatically update indexes when you change the source collection.

So if you make collection "dogs" and insert a new dog you can do this:

```js
const dogs = await db.collection("dogs")
await dogs.insert([{ name: "Jeff" }, { name: "Joe" }]).many()
await dogs.createIndex({ name: 1 })
await dogs.insert({ name: "Jack" }).many()
console.log(await dogs.find().many()) // Jack shows up
console.log(await dogs.find().sort({ name: 1 }).many()) // Jack does not show up
await dogs.createIndex({ name: 1 })
console.log(await dogs.find().sort({ name: 1 }).many()) // Jack shows up
```

**Comment by ArtemGr** [comment]
Congratz!
What's next on your plate?  D

**Comment by giraffekey** [comment]
I still need to write some unit tests and documentation.

However I think the best way to test it and stabilize the API is to take it into production - which is why I am going to build an actual application with it.

**Comment by ArtemGr** [comment]
![image](https://user-images.githubusercontent.com/41847/105352145-6149fb00-5ba2-11eb-88b4-41417e9b8378.png)

Woot! D
