### ISSUE TITLE
generate and upload gource GIFs

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/bounty#9]
The goal is to feature gource snippets in a github README

**Comment by ArtemGr** [comment]
@GiraffeKey, so if we post an animated GIF to Sia, will it have a web URL (for GitHub to load it into a README)?

**Comment by ArifSanaullah** [comment]
@ArtemGr I'm done with creating gif. Now working to publish that gif onto a static URL so that I can use that URL inside README.md.
=> https://github.com/ArifSanaullah/gource/blob/main/.github/workflows/gource.yaml

**Comment by ArtemGr** [comment]
Implemented by @ArifSanaullah at https://github.com/ArifSanaullah/gource
